/*
 * Copyright 2020 Java Programmer Indonesia.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.youtubeplayer.controller.swing;

import com.youtubeplayer.util.vlc.VlcUtil;
import javax.swing.ImageIcon;

/**
 *
 * @author rizal
 */
public class PlayerContainer extends javax.swing.JFrame {

    /**
     * Creates new form Container
     */
    public PlayerContainer() {
        initComponents();
        setIconImage(new ImageIcon(
                getClass().getClassLoader().getResource("logo-min.png")).getImage());
        initVideoPlayer();
    }
    
    private void initVideoPlayer(){
        VlcUtil vlcUtil = new VlcUtil();
        videoPlayer.setMediaPlayer(vlcUtil.getMediaPlayer());
        videoPlayer.init(this);
        vlcUtil.registerCanvas(videoPlayer.getCanvas());
    }
    
    public void play(){
        videoPlayer.play();
    }

    public void pause(){
        videoPlayer.pause();
    }
    
    public void prepare(String title, String url){
        setTitle(title);
        videoPlayer.prepare(url);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        videoPlayer = new com.youtubeplayer.controller.swing.player.VideoPlayer();

        setTitle("Player");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 270));
        setPreferredSize(new java.awt.Dimension(400, 270));
        getContentPane().add(videoPlayer, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerContainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.youtubeplayer.controller.swing.player.VideoPlayer videoPlayer;
    // End of variables declaration//GEN-END:variables
}
